apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: oy74qt8lx-go 
  janus-idp.io/tekton: oy74qt8lx-go
  backstage.io/kubernetes-id: oy74qt8lx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oy74qt8lx-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml